// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPWpj8yYQUx96L15k7z1mdqRRIUqtka1o',
    appId: '1:352014365303:android:7493a3972c5a973fbc8c72',
    messagingSenderId: '352014365303',
    projectId: 'feria-app-e7307',
    storageBucket: 'feria-app-e7307.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7WFMJFGexrs--hC5IhNFyJRilKVV0X4w',
    appId: '1:352014365303:ios:a1fb18bf1133ced4bc8c72',
    messagingSenderId: '352014365303',
    projectId: 'feria-app-e7307',
    storageBucket: 'feria-app-e7307.appspot.com',
    iosBundleId: 'com.feriaapp.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7WFMJFGexrs--hC5IhNFyJRilKVV0X4w',
    appId: '1:352014365303:ios:a1fb18bf1133ced4bc8c72',
    messagingSenderId: '352014365303',
    projectId: 'feria-app-e7307',
    storageBucket: 'feria-app-e7307.appspot.com',
    iosBundleId: 'com.feriaapp.com',
  );
}
